/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CameraPreview {
        "drawOverlay"?: boolean;
        "license"?: string;
    }
}
declare global {
    interface HTMLCameraPreviewElement extends Components.CameraPreview, HTMLStencilElement {
    }
    var HTMLCameraPreviewElement: {
        prototype: HTMLCameraPreviewElement;
        new (): HTMLCameraPreviewElement;
    };
    interface HTMLElementTagNameMap {
        "camera-preview": HTMLCameraPreviewElement;
    }
}
declare namespace LocalJSX {
    interface CameraPreview {
        "drawOverlay"?: boolean;
        "license"?: string;
    }
    interface IntrinsicElements {
        "camera-preview": CameraPreview;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "camera-preview": LocalJSX.CameraPreview & JSXBase.HTMLAttributes<HTMLCameraPreviewElement>;
        }
    }
}
