/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AnalysingResult, Resolution } from "./definitions";
export namespace Components {
    interface CameraPreview {
        "active"?: boolean;
        "desiredCamera"?: string;
        "desiredResolution"?: Resolution;
        "drawOverlay"?: boolean;
        "getAllCameras": () => Promise<MediaDeviceInfo[]>;
        "getVideoElement": () => Promise<HTMLVideoElement>;
        "updateAnalysingResults": (results: AnalysingResult[]) => Promise<void>;
    }
}
export interface CameraPreviewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCameraPreviewElement;
}
declare global {
    interface HTMLCameraPreviewElement extends Components.CameraPreview, HTMLStencilElement {
    }
    var HTMLCameraPreviewElement: {
        prototype: HTMLCameraPreviewElement;
        new (): HTMLCameraPreviewElement;
    };
    interface HTMLElementTagNameMap {
        "camera-preview": HTMLCameraPreviewElement;
    }
}
declare namespace LocalJSX {
    interface CameraPreview {
        "active"?: boolean;
        "desiredCamera"?: string;
        "desiredResolution"?: Resolution;
        "drawOverlay"?: boolean;
        "onOpened"?: (event: CameraPreviewCustomEvent<void>) => void;
    }
    interface IntrinsicElements {
        "camera-preview": CameraPreview;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "camera-preview": LocalJSX.CameraPreview & JSXBase.HTMLAttributes<HTMLCameraPreviewElement>;
        }
    }
}
